python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path dataset/SMAP \
  --model_id SMAP \
  --model PerimidFormer \
  --data SMAP \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 8 \
  --layers 8 \
  --chan_in 25 \
  --top_k 4 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --train_epochs 1 \
  --itr 3 \
  --learning_rate 0.0001