python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path dataset/PSM \
  --model_id PSM \
  --model PerimidFormer \
  --data PSM \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 8 \
  --layers 4 \
  --chan_in 25 \
  --top_k 4 \
  --anomaly_ratio 1 \
  --batch_size 8 \
  --train_epochs 1 \
  --learning_rate 0.005 \
  --itr 3