python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path dataset/SMD \
  --model_id SMD \
  --model PerimidFormer \
  --data SMD \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 8 \
  --layers 3 \
  --chan_in 38 \
  --top_k 6 \
  --anomaly_ratio 0.5 \
  --batch_size 8 \
  --train_epochs 3 \
  --itr 3 \
  --learning_rate 0.005