python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path dataset/MSL \
  --model_id MSL \
  --model PerimidFormer \
  --data MSL \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 8 \
  --layers 5 \
  --chan_in 55 \
  --top_k 2 \
  --anomaly_ratio 1 \
  --batch_size 16 \
  --train_epochs 1 \
  --itr 3 \
  --learning_rate 0.0001