python -u run.py \
  --task_name classification \
  --is_training 1 \
  --root_path dataset/SpokenArabicDigits/ \
  --model_id SpokenArabicDigits \
  --model PerimidFormer \
  --data UEA \
  --layers 2 \
  --batch_size 2 \
  --d_model 64 \
  --top_k 2 \
  --des 'Exp' \
  --itr 3 \
  --learning_rate 0.0005 \
  --train_epochs 20 \
  --patience 5 \
  --chan_in 13